### ISSUE TITLE
Apsim Week

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ReferencePanel#73] opened 2020-10-12 05:39 UTC
To assist discussion in the upcoming RP meeting (and subsequent AI SC meeting), thoughts and/or input is requested for the planned APSIM event (April 2021). 

- Currently planning the same (if not very similar) format and content to that originally planned in March 2020.
- Currently agreed to make the call by 31/1/21 to proceed or not.

Factors impacting the decision/go ahead:

- Uncertainty with regard to local borders opening (or remaining opening).  Victoria still no confirmed date to opening.
- Uncertainty with regard to the AU/NZ bubble.  If this doesn't open, leaves a number of key presenters/facilitators unable to attend.
- Current rooms booked for event have much reduced seating capacity and provides for only 29 seats for the APSIM Symposium and range of 9-20 for workshops.  Advice received has stated that this is the capacity for the foreseeable future.
-  Uncertainty with regard to organisations still not allowing travel for conferences/training workshops.  

Options for discussion

- Cancel event and refund all monies
- Leave decision until 31/1/21 
- Look for other rooms/venue able to hold required numbers
- Provide a different format:
    - Current format delivered online  (possible for Symposium, more difficult if not impossible for most of the training workshops) 
    - Revised format - a one day event covering more workshop topics as an science/software update.  Sessions recorded and used as part of training material

Consultation with attendees over these points is expected at some stage

**Comment by sarahcleary** [comment] 2020-10-12 08:14
@APSIMInitiative/reference-panel; @hut104; @her123; @lie112  - for thoughts/input

**Comment by sno036** [comment] 2020-10-12 21:17
Yes - "Cancel event" - I think this decision is actually inevitable and it is not feasible to plan for alternatives while it is technically on the table. 

Maybe not - " and refund all monies" - if there is an online alternative then the funds could be applied there

Seriously consider - "Revised format" but not as "a one day event covering more workshop topics as an science/software update.". Online events are tiring and a full day is unlikely to work. It is I think better to run sessions for two hours (can do two hours, a break and two hours) at different times of the day (possibility of getting more people).

Yes - "Sessions recorded and used as part of training material" but they will need editing I would think

Don't underestimate the amount of prep time needed - it will be more than a face-to-face.

**Comment by her123** [comment] 2020-10-12 22:31
To go ahead at this stage is an optimistic view. Travel and meetings have the possibility of opening more up or closing down again. We have no way of telling which at this stage. I don't think it will be more certain by January. Just yesterday in Canberra an Easter 2021 folk festival was cancelled.
It may take more effort to design webinars on specified topics but I think that @sno036 's idea of two hour sessions may be good. Even if they were at a higher introductory level people will still benefit from them.

**Comment by Keith-Pembleton** [comment] 2020-10-12 23:11
Canceling give us some certainty and enables us to plan a new event in what ever form it takes.  I agree with @sno036 re online events and the structure.  
Advanced training is the sticking point.  Will need to put some thought into how we can deliver that.

**Comment by EnliWang** [comment] 2020-10-12 23:34
I agree with cancelling the event and changing it to online as suggested by @sno036. At the moment, many international conferences/symposiums are changing to the online format.

For training, I would think that delivering the general session would be OK. The problem is in the hand-on sessions. Is there a way to do separate screen-sharing with different trainers? Just a thought.

**Comment by lie112** [comment] 2020-10-13 01:28
I think cancelling the event is the most appropriate option given the current/future uncertainty. 
I'd like to earn royalties from the model that can predict April 2021. Not suggesting I know how to build it right now.

I agree with all suggestions around an online event (especially  @sno036).

My ideas include: 

- hold a 2 hour session at the same time each week over seven or eight weeks (8-9 sessions) with each targeted toward an area/component of the APSIM (much like the sessions/workshops proposed). Format could be 1 hour of presentations (1x60min, 2x30min, 3x20min etc), followed by case study/tutorial, plus Q&A. This would actually allow people to access more than was possible at the symposium due to conflicts between timing of workshops. People can block out this time and have clear concentration for this period. The session could remain open while there is still interest and discussion. Based on interest there may be concurrent sessions or have this run longer.

- I am not sure about the best format for workshops. A live session with someone working with the model could be useful for a range of users, especially if this is recorded and available later as a resource. In this session those on the call would be free to ask questions at any time, which is not possible in a recorded walk though example, or moderated via chat session and a session moderator. Smaller group size per trainer sessions could improve the interaction but there may not be enough competent trainers when they too rely on each other for answers..

- There could be a fee for each session, and a reduced full package fee the same as current payment. Invitations with connection links would only go to those who have registered.

- As we have all the infrastructure for the online sessions, and most people are now familiar with this format, there could be a range of other small value adding options such as - specific user get togethers and discussions - science sessions - coding sessions - get to know a developer - get to know RP, APSIM Quiz with prizes, Student awards etc. These wouldn't take much to organise but could benefit the APSIM community. This would give the multi-week series a special feel, adding more of the casual conference interactions, and seem more beneficial than sitting through a few polished presentations.

**Comment by sarahcleary** [comment] 2020-10-25 10:24
@sme016

**Comment by sarahcleary** [comment] 2020-11-09 04:02
@APSIMInitiative/reference-panel - following on from the discussion in last week's RP meeting, it was agreed to find an alternative program to that originally planned for March 2020. This may include polling current registrants for their input/requirements.  I look forward to hearing suggestions for moving forward.

**Comment by sarahcleary** [comment] 2020-11-09 04:03
Suggestion from @sme016  

Idea for structure: I recently attend (online, free) the Forest Growers Research conference, which I thought went well for online delivery of a conference. That meeting will eventually be available at this link https://fgr.nz/programmes/conferences/, which I assume you could check. Presenters provided a pre-recorded video that kept to the time limit (maybe some editing was done too). After a block of those presentations, there was participants lodged questions via the chat, through a moderator, and the presenter answered live.  

For workshops, time might have to be made available for each participant to share their screen and progress, ask questions and receive answers, which the rest of the group could also interact with. However, my format was going to be mainly demonstration with live building and editing of simulations by me. For a few participants, it would be useful to provide ‘homework’ and send the participants away for a day/night before checking, commenting and working further on their individual case studies in a group setting.

**Comment by yashvirchauhan** [comment] 2020-11-09 04:11
Although we have entered a relatively better period with respect to Covid-19c cases, I believe, it will not be possible to hold any face to face meeting until a vaccine is developed. mass produced and mass inoculated. It is likely to happen by the second half of the next year. Can we have one more postponement of the meeting to September? We can  have a couple virtual trainings sessions, if training need is very strongly felt leaving a larger number to covered in the face to face meeting.

**Comment by sarahcleary** [comment] 2020-11-09 04:22
Given the uncertainty, I would be hesitant to postpone, again.  We can 'easily' reorganise a symposium when the time is right. 
The general consensus was to provide an alternate offering in March/April 2021 but recognise the original format is not suitable for online delivery.  @lie112 and @sme016 have provided some suggestions and @Keith-Pembleton might like to provide more detail on some of his thoughts which we only briefly touched on during the meeting (due to time).  I would suggest a format - about a day's worth (whether it is one full day or spread over a period as proposed above) of presentations/tutorials on issues that are relevant to current registrants.  I would assume the topics would be similar to that we would be covering in some of the advanced training workshops (but much shorter versions/narrower scope) and/or some of the keynote presentations.  We did suggest of asking current attendees to ask for feedback - whether we ask for topics or poll for interest in a range of topics/areas

**Comment by Keith-Pembleton** [comment] 2020-11-11 06:47
My half formed thoughts from the last reference panel meeting were:
The symposium presentations could be done online via any number of webinar platforms.  We will miss out on the networking opportunities that come with a face to face symposium. We could try some sort of zoom "speed dating" thing but not sure if that will work.  I know other events that have been forced online have tried it, but I am yet to experience it myself so can't comment.  

Delivering advanced training is the challenge, but I think if we had some generic advanced modeling excises developed for each advance training topic for participants to work through to familiarise themselves with the concepts that we are trying to explain followed up by a 20 minute (or however long) one on one video chat with the trainer to discuss and seek advice on their particular use case that might get us close to what we wanted to achieve out of the advanced training.

**Comment by sarahcleary** [comment] 2020-11-11 09:24
My impression from the RP discussion was there was reasonable support for the "generic advanced modelling exercises developed for each advance training topic".  And if my interpretation of the conversation is correct, this was where the discussion preceding the "poll interest/suggestions" from attendees.  Is this right?  

I had envisaged the exercises would form part of the online delivery and potentially allow for some breakout rooms or an alterative follow up forum - whether via video, email, github etc..  

Taking on the suggestion about from Phil - either some of the symposium topics and/or these generic exercises/problems could be pre-recorded and questions could be answered live with the presenter.  

What do people think - @APSIMInitiative/reference-panel??

**Comment by hol353** [comment] 2020-11-12 21:34
I guess my feeling is that there is no urgency to run an APSIM week right now. Is there any harm moving it to autumn 2022 when there should be more certainty around COVID and we can do it face-to-face and get all the benefits of networking etc. Otherwise we run it as an online event and lose most of the benefits of APSIM week.  What do we get out of an online event for the effort we put in?

**Comment by sarahcleary** [comment] 2020-11-16 07:21
@APSIMInitiative/steering-committee - welcome your thoughts and comments on this topic

**Comment by sarahcleary** [comment] 2020-11-16 07:33
@GlynFrancis1 and @krlamkey - now added to the SC GitHub group.

**Comment by peter-devoil** [comment] 2020-11-17 00:14
I suspect that an indeterminate series of postponements will eventually wear thin with participants, and that we are now at a stage where the honest policy is to cancel it and present a covid era solution - online. We don't have to present the same thing, indeed an online format should be quite different than what we developed. If we're thinking about a different format, we began with the idea to foster a community of apsim users and promote its use, and our online activity should reflect that. 

I'm wondering that if making videos or conducting online meetings to present our work is so intimidating, should we spend resources to pay professionals to assist with it -  working in conjunction with our existing presenters who can describe/articulate the problem far better than an outsider. Certainly each of our home orgs have media units tasked with just that. 

For a start, one of the main components of the symposium was the opportunity to explain NG and demonstrate a pathway out of classic to use the new technology; likewise the workshops ended up with repeat sessions on PMF and migration - these topics are of significant interest to our users but our online resources address them in an ad-hoc manner (and I'm not casting shade on the good people who've made them).

**Comment by sarahcleary** [comment] 2020-11-17 01:16
I agree that we shouldn't continually postpone the event.  We can reorganise a similar event (updated content but similar format) when there is more certainty.  Given the last few days in South Australia, I think we would be foolish to believe a face to face event involving O/S participants/presenters would be possible in 2021. 

I think we've had some good options raised both on this issue as well as in the RP meetings with regard to online delivery. 

Maybe we need to step back and really nail down what the AI wishes to achieve from an online event to ensure what we provide ticks some agreed criteria (or agree that it can't be achieved virtually).  I have viewed this through a communication and networking lens.  We have been discussing growing the APSIM community and 'APSIM Week' would have been a positive step.  It has been also mentioned that these events result in a two way communication around what other users/developers do/like/struggle with - which can feedback into further development.  And of course, networking can result in significant benefits.  

I personally liked the idea that @lie112 put forward above around shorter targeted sessions over a number of weeks.  We have had 40+ people interested in a large number of the advanced workshop topics and I note that the training wouldn't (in most cases) be able to be provided in the format originally envisaged, I sure there would be a way to deliver information on topic that would be helpful for users/developers.  

Would be interested in thoughts from others.

**Comment by sarahcleary** [comment] 2021-01-07 00:59
Closing issue as APSIM Week has been cancelled.

**Closed as completed by sarahcleary** 2021-01-07 00:59 UTC
Labels: Action
